// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    BigTitle: typeof import('./src/components/BigTitle.vue')['default']
    Bubbles: typeof import('./src/components/Bubbles.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    EcoLogo: typeof import('./src/components/EcoLogo.vue')['default']
    EcoStudios: typeof import('./src/components/EcoStudios.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IndexSection: typeof import('./src/components/IndexSection.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    WorkCard: typeof import('./src/components/WorkCard.vue')['default']
    WorksSection: typeof import('./src/components/WorksSection.vue')['default']
  }
}

export { }
