<template>
  <div
    id="showNotification"
    v-if="showNotification"
    class="absolute z-40 w-96 bg-gray-800 rounded-md py-2 px-4 shadow-lg bottom-0 wobble-hor-top"
  >
    <h1 class="font-bold text-2xl text-gray-50">Thank you!</h1>
    <p class="font-medium text-lg text-gray-50">Your owl has been sent</p>
  </div>
</template>

<script>
export default {
  props: {
    show: Boolean,
  },
  data: () => ({
    showNotification: false,
  }),
  watch: {
    show(val, oldVal) {
      const notEle = document.getElementById("showNotificacion");
      if (val) {
        this.showNotification = true;
        setTimeout(this.test, 4000);
      }
    },
  },

  methods: {
    test() {
      console.log("test");
      this.showNotification = false;
    },
  },
};
</script>

<style scoped>
.wobble-hor-top {
  -webkit-animation: wobble-hor-top 0.8s both;
  animation: wobble-hor-top 0.8s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-4-23 17:28:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-top {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(6deg);
    transform: translateX(-30px) rotate(6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(-6deg);
    transform: translateX(15px) rotate(-6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(3.6deg);
    transform: translateX(-15px) rotate(3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(-2.4deg);
    transform: translateX(9px) rotate(-2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(1.2deg);
    transform: translateX(-6px) rotate(1.2deg);
  }
}
@keyframes wobble-hor-top {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(6deg);
    transform: translateX(-30px) rotate(6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(-6deg);
    transform: translateX(15px) rotate(-6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(3.6deg);
    transform: translateX(-15px) rotate(3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(-2.4deg);
    transform: translateX(9px) rotate(-2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(1.2deg);
    transform: translateX(-6px) rotate(1.2deg);
  }
}
</style>
